language: go
go:
- 1.8.x
- master
matrix:
  allow_failures:
    - go: master
env:
- BUILD_GOOS=linux BUILD_GOARCH=amd64
- BUILD_GOOS=darwin BUILD_GOARCH=amd64
- BUILD_GOOS=windows BUILD_GOARCH=amd64
go_import_path: go.rls.moe/misc/discord.mods
install:
- go get -u github.com/gopherjs/gopherjs
- go get -u github.com/gopherjs/jquery
- go get -u github.com/GeertJohan/go.rice
- go get -u github.com/GeertJohan/go.rice/rice
script:
- GOARCH=$BUILD_GOARCH GOOS=$BUILD_GOOS ./test_and_build.sh